//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home_Weather_Hub
{


    public partial class Charts
    {

        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Home_Weather_Hub.ws Master
        {
            get
            {
                return ((Home_Weather_Hub.ws)(base.Master));
            }
        }
    }
}
